[phases.setup]
nixPkgs = ["...", "git", "python311", "python311Packages.pip"]
aptPkgs = ["ffmpeg"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "pip install flask google-api-python-client google-auth-oauthlib gunicorn"
]

[start]
cmd = "node app.js"
