[phases.setup]
nixPkgs = ["...", "git", "python3"]
aptPkgs = ["ffmpeg"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "python3 -m pip install flask google-api-python-client google-auth-oauthlib"
]

[start]
cmd = "node app.js"
